name: py39
channels:
  - defaults
dependencies:
  - python=3.9
  - pytorch==2.3.1
  - torchvision==0.18.1
  - pytorch-cuda=11.8
  - torchaudio==2.3.1
  - cuda-toolkit
  - ninja
  - gxx_linux-64=11.4.0
  - openblas-devel
